### ISSUE TITLE
[404]: owner, repo or path is invalid

### ISSUE THREAD

**Issue by AnisTaluqdar** [ibrahemesam/repo-view#5]
![image](https://github.com/ibrahemesam/repo-view/assets/41234183/3363448f-9b7f-4892-ba26-7c5ee7fe0714)

Not working, I did everything as you said but the error is occurring.

**Comment by ibrahemesam** [comment]
This 404 error means that URL resource does NOT exist. It may happen in 3 cases:
- the repo-name in the is incorrect (check whitespaces, upper/lower case...etc)
- repo owner is incorrect:
    - the repo may be owned by a github organization not a normal username. It must be the same as in github.com/\<owner\>/\<repo\>
    - there may be extra whitespace or uppercase char...etc
- path is incorrect: the path in url params points to a non-existing file or directory

One more possible reason: the github token doesn't have read access to repository content (check token creation instructions)

**Comment by AnisTaluqdar** [comment]
not worked for me, also why we need to put username while repository has already username with it? 

![image](https://github.com/ibrahemesam/repo-view/assets/41234183/2211f86e-3512-4112-a1dc-3078fd401557)
https://ibrahemesam.github.io/repo-view//?

token=6769746875625f7061745f3131414a325336425930374d5766345465466f57614f5f7854476b4c4b4464714e574376364168784a76326a6532656330514279367262394c3064515a79736d6c704c34484d5a5941556e724c433559584f_enc&owner=AnisTaluqdar&repo=https://github.com/AnisTaluqdar/dudl

where is the wrong?

**Comment by ibrahemesam** [comment]
Sorry, I think the README isn't clear enough. I'll fix that.
The repo name should be just its name not the whole url.
ie: be "dudl" instead of "https://github.com/AnisTaluqdar/dudl"
___
So, your url should be: [URL](https://ibrahemesam.github.io/repo-view/?token=6769746875625f7061745f3131414a325336425930374d5766345465466f57614f5f7854476b4c4b4464714e574376364168784a76326a6532656330514279367262394c3064515a79736d6c704c34484d5a5941556e724c433559584f_enc&owner=AnisTaluqdar&repo=dudl)
For security reasons, please delete that token and create a new SECRET one

**Comment by AnisTaluqdar** [comment]
thanks

**Comment by ibrahemesam** [comment]
You are welcome
